apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
        - name: frontend
          image: <your-frontend-image>:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend
spec:
  selector:
    app: bookstore-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 